# Generated by Django 4.1.4 on 2022-12-23 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PROCESSOR', 'PROCESSOR'), ('GRAPHICS_CARD', 'GRAPHICS_CARD'), ('RAM', 'RAM'), ('STORAGE_DEVICES', 'STORAGE_DEVICES'), ('MONITOR', 'MONITOR')], max_length=30),
        ),
    ]
