# Generated by Django 4.1.4 on 2022-12-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_added_date_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
