# Generated by Django 4.1.4 on 2022-12-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_wishlist_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
