# Generated by Django 4.1.4 on 2022-12-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_price_alter_wishlist_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
