# Generated by Django 4.1.4 on 2022-12-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_quantity_wishlist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PROCESSOR', 'PROCESSOR'), ('GRAPHICS_CARD', 'GRAPHICS_CARD'), ('RAM', 'RAM'), ('STORAGE_DEVICES', 'STORAGE_DEVICES'), ('MONITOR', 'MONITOR')], max_length=30)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('stock', models.CharField(choices=[('OUT_OF_STOCK', 'OUT_OF_STOCK'), ('IN_STOCK', 'IN_STOCK')], max_length=15)),
            ],
        ),
    ]
