# Generated by Django 4.1.4 on 2023-01-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_order_payment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_item',
        ),
    ]
