# Generated by Django 4.1.4 on 2023-01-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_order_ordered_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_item',
            field=models.ManyToManyField(to='product.wishlist'),
        ),
    ]
