# Generated by Django 4.1.4 on 2023-01-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_order_ordered_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_item',
            field=models.ManyToManyField(blank=True, null=True, to='product.wishlist'),
        ),
    ]
