# Generated by Django 4.1.4 on 2023-01-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Completed', 'Completed')], default='Pending', max_length=15),
        ),
    ]
