PROCESSOR = 'PROCESSOR'
GRAPHICS_CARD = 'GRAPHICS_CARD'
RAM = 'RAM'
STORAGE_DEVICES = 'STORAGE_DEVICES'
MONITOR = 'MONITOR'
LAPTOP = 'LAPTOP'
MOTHERBOARD = 'MOTHERBOARD'
CASE = "CASE"
POWERSUPPLY = "POWERSUPPLY"

CATEGORY_CHOICES = (
    (PROCESSOR, "PROCESSOR"),
    (GRAPHICS_CARD, "GRAPHICS_CARD"),
    (RAM, "RAM"),
    (STORAGE_DEVICES, "STORAGE_DEVICES"),
    (MONITOR, "MONITOR"),
    (LAPTOP, "LAPTOP"),
    (MOTHERBOARD, "MOTHERBOARD"),
    (CASE, "CASE"),
    (POWERSUPPLY, "POWERSUPPLY"),
)

SOLD = 'SOLD'
IN_STOCK = 'IN_STOCK'

ITEM_STOCK = (
    (SOLD, "SOLD"),
    (IN_STOCK, "IN_STOCK")
)

INTEL = 'INTEL'
AMD = 'AMD'
MSI = 'MSI'
NVIDIA = 'NVIDIA'
ASUS = 'ASUS'


COMPANY = (
    (INTEL, "INTEL"),
    (AMD, "AMD"),
    (MSI, "MSI"),
    (NVIDIA, "NVIDIA"),
    (ASUS, "ASUS")
)


METHOD = (
    ("Cash On Deliver", "Cash on Delivery"),
    ("Khalti", "Khalti"),

)